CXX?=g++
CXXFLAGS?=-std=c++11 -g -Wall
OBJS=bot.o bot_Thomas.o bot_Eric.o bot_Eugen.o bot_Lucian.o
COMMON=../util/card.cpp ../util/require.h ../util/gamelist.h

all: $(OBJS)

.PHONY: clean
clean:
	rm -f *\.o
